sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.2'
branches:
  only:
    - master
script:
  - npm run test
after_script:
  - ./node_modules/.bin/gulp coveralls
after_success:
  - npm run semantic-release
